version: "3.4"

services:
  app:
    build:
      context: .
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - sync
      - redis
    environment:
      DATABASE_URL: "postgres://drinqs:password@db:5432/drinqs"
      SECRET_KEY_BASE: "abcdefghijklmnopqrstuvwxyz"
      DJANGO_DEBUG: "True"
      REDIS_URL: "redis://redis:6379/1"
    ports:
      - "8000:8000"
      - "4000:4000"

  db:
    image: postgres:10.3-alpine
    environment:
      POSTGRES_USER: drinqs
      POSTGRES_PASSWORD: password
      POSTGRES_DB: drinqs
    ports:
      - "15432:5432"

  redis:
    image: redis:alpine
    ports:
      - "16379:6379"
