# Generated by Django 3.1.5 on 2021-01-06 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('alcoholic', models.IntegerField(blank=True, choices=[(0, 'not available'), (1, 'alcoholic'), (2, 'non alcoholic')])),
                ('category', models.CharField(blank=True, max_length=128)),
                ('preparation', models.TextField(blank=True)),
                ('thumbnailurl', models.CharField(blank=True, max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField(default=False)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinqsapp.cocktail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IngredientTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('user', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('ingredienttag', models.ManyToManyField(blank=True, to='drinqsapp.IngredientTag')),
            ],
        ),
        migrations.CreateModel(
            name='CocktailIngredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.IntegerField(choices=[(0, 'ml'), (1, 'oz'), (2, 'cup'), (3, 'tsp'), (4, 'Tbsp'), (5, 'package')])),
                ('amount', models.FloatField()),
                ('position', models.SmallIntegerField(blank=True)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinqsapp.cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinqsapp.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='glass',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='drinqsapp.glass'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(through='drinqsapp.CocktailIngredients', to='drinqsapp.Ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='userreview',
            field=models.ManyToManyField(through='drinqsapp.Review', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('user', 'cocktail'), name='unique_review'),
        ),
        migrations.AddConstraint(
            model_name='cocktailingredients',
            constraint=models.UniqueConstraint(fields=('cocktail', 'ingredient'), name='unique_cocktailingredients'),
        ),
        migrations.AddConstraint(
            model_name='cocktailingredients',
            constraint=models.UniqueConstraint(fields=('cocktail', 'position'), name='unique_cocktailposition'),
        ),
    ]
