# Generated by Django 3.1.5 on 2021-01-19 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinqsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.IntegerField(choices=[(0, 'ml'), (1, 'oz'), (2, 'cup'), (3, 'tsp'), (4, 'Tbsp'), (5, 'package')])),
                ('amount', models.FloatField()),
                ('position', models.SmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='alcoholic',
            field=models.IntegerField(blank=True, choices=[(0, 'not available'), (1, 'alcoholic'), (2, 'non alcoholic')], null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='glass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drinqsapp.glass'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='preparation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='thumbnailurl',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='cocktailingredient',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinqsapp.cocktail'),
        ),
        migrations.AddField(
            model_name='cocktailingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drinqsapp.ingredient'),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(through='drinqsapp.CocktailIngredient', to='drinqsapp.Ingredient'),
        ),
        migrations.DeleteModel(
            name='CocktailIngredients',
        ),
        migrations.AddConstraint(
            model_name='cocktailingredient',
            constraint=models.UniqueConstraint(fields=('cocktail', 'ingredient'), name='unique_cocktailingredients'),
        ),
        migrations.AddConstraint(
            model_name='cocktailingredient',
            constraint=models.UniqueConstraint(fields=('cocktail', 'position'), name='unique_cocktailposition'),
        ),
    ]
