# Generated by Django 3.1.5 on 2021-01-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinqsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktailingredient',
            name='amount',
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='measurement',
            field=models.CharField(max_length=128),
        ),
    ]
