# Generated by Django 3.1.5 on 2021-01-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinqsapp', '0002_auto_20210119_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
