# Generated by Django 3.1.5 on 2021-01-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinqsapp', '0002_auto_20210124_1259'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cocktailingredient',
            name='unique_cocktailingredients',
        ),
        migrations.RemoveConstraint(
            model_name='cocktailingredient',
            name='unique_cocktailposition',
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='measurement',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
