# Generated by Django 3.1.5 on 2021-01-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinqsapp', '0003_auto_20210119_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='userreview',
            new_name='reviews',
        ),
        migrations.RenameField(
            model_name='cocktail',
            old_name='thumbnailurl',
            new_name='thumbnail_url',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='ingredienttag',
            new_name='ingredient_tags',
        ),
        migrations.RenameField(
            model_name='ingredienttag',
            old_name='user',
            new_name='users',
        ),
        migrations.RemoveField(
            model_name='review',
            name='likes',
        ),
        migrations.AddField(
            model_name='review',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
