# Generated by Django 3.1.5 on 2021-01-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinqsapp', '0005_trigram_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='bookmarked',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='liked',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
