# Generated by Django 3.1.5 on 2021-01-20 12:01

import autoslug
from django.db import migrations, models


def add_slugs(apps, schema_editor):
    Cocktail = apps.get_model('drinqsapp', 'Cocktail')
    for cocktail in Cocktail.objects.all():
        cocktail.slug = autoslug.utils.slugify(cocktail.name)
        cocktail.save()

def remove_slugs():
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('drinqsapp', '0005_auto_20210120_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='slug',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RunPython(add_slugs, remove_slugs),
    ]
