# Generated by Django 3.1.6 on 2021-02-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinqsapp', '0006_auto_20210130_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='bookmarked',
            field=models.BooleanField(default=False),
        ),
    ]
