# Generated by Django 3.1.6 on 2021-02-06 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinqsapp', '0006_auto_20210130_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocktailCondensedMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
    ]
