# Generated by Django 3.1.5 on 2021-01-20 12:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinqsapp', '0006_cocktail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, max_length=128, populate_from='name', sep='--', unique=True),
        ),
    ]
