# Generated by Django 3.1.6 on 2021-02-09 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinqsapp', '0007_cocktailcondensedmatrix'),
        ('drinqsapp', '0007_auto_20210206_1500'),
    ]

    operations = [
    ]
