# Generated by Django 3.1.5 on 2021-01-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinqsapp', '0007_auto_20210120_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cocktail',
            old_name='reviews',
            new_name='reviewers',
        ),
    ]
