name: Continuous Integration
on: push

jobs:
  pylint:
    name: Run PyLint
    runs-on: ubuntu-20.04
    steps:
    - name: GitHub Action for pylint
      uses: cclauss/GitHub-Action-for-pylint@0.7.0
