name: Continuous Integration
on: push

jobs:
  pylint:
    name: Run PyLint
    runs-on: ubuntu-20.04
    steps:
    - name: checkout-repo
      uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - run: pip install pylint --upgrade
    - run: pylint **/*.py
